Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -95,40 +95,41 @@ stages:
       runOnce:
         deploy:
           steps:
-          # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
-          #   displayName: 'Install Terraform latest'
-          # - bash: |
-          #     terraform init -input=false
-          #   displayName: Terraform Init
-          #   env:
-          #     AWS_ACCESS_KEY_ID:      $(AWS_ACCESS_KEY_ID)
-          #     AWS_SECRET_ACCESS_KEY:  $(AWS_SECRET_ACCESS_KEY)
-          #     AWS_DEFAULT_REGION:     $(TF_BACKEND_S3_REGION)
-          #     AWS_SESSION_TOKEN:      $(AWS_SESSION_TOKEN)
-          #   workingDirectory: '$(Pipeline.Workspace)/rest_api/s/infrastructure'
           - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
             displayName: 'Install Terraform latest'
-          - task: AWSShellScript@1
-            inputs:
-              awsCredentials: '${{ parameters.awsConnection }}'
-              regionName: 'eu-central-1'
-              scriptType: 'inline'
-              inlineScript: |
-                terraform -chdir=${{ parameters.path }} init \
-                    -backend-config="bucket=$(TF_BACKEND_S3_BUCKET)" \
-                    -backend-config="key=$(TF_BACKEND_S3_BUCKET_KEY)" \
-                    -backend-config="region=$(TF_BACKEND_S3_REGION)" \
-                    -backend-config="dynamodb_table=$(TF_BACKEND_S3_DYNAMODB_TABLE)"
-                terraform -chdir=${{ parameters.path }} validate
-                terraform -chdir=${{ parameters.path }} plan -detailed-exitcode
-                echo $? > $(Pipeline.Workspace)/PLAN_CODE
-                echo "##vso[task.setvariable variable=PLAN_CODE]$(cat $(Pipeline.Workspace)/PLAN_CODE)"
-              disableAutoCwd: true
-              workingDirectory: '$(Pipeline.Workspace)/rest_api/s'
-              failOnStandardError: true
+          - bash: |
+              terraform init -input=false
+              terraform plan
+            displayName: Terraform Init
             env:
-              AZDO_PERSONAL_ACCESS_TOKEN: $(AZDO_PERSONAL_ACCESS_TOKEN)
-            displayName: Validate Terraform
+              AWS_ACCESS_KEY_ID:      $(AWS_ACCESS_KEY_ID)
+              AWS_SECRET_ACCESS_KEY:  $(AWS_SECRET_ACCESS_KEY)
+              AWS_DEFAULT_REGION:     $(TF_BACKEND_S3_REGION)
+              AWS_SESSION_TOKEN:      $(AWS_SESSION_TOKEN)
+            workingDirectory: '$(Pipeline.Workspace)/rest_api/s/infrastructure'
+          # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
+          #   displayName: 'Install Terraform latest'
+          # - task: AWSShellScript@1
+          #   inputs:
+          #     awsCredentials: '${{ parameters.awsConnection }}'
+          #     regionName: 'eu-central-1'
+          #     scriptType: 'inline'
+          #     inlineScript: |
+          #       terraform -chdir=${{ parameters.path }} init \
+          #           -backend-config="bucket=$(TF_BACKEND_S3_BUCKET)" \
+          #           -backend-config="key=$(TF_BACKEND_S3_BUCKET_KEY)" \
+          #           -backend-config="region=$(TF_BACKEND_S3_REGION)" \
+          #           -backend-config="dynamodb_table=$(TF_BACKEND_S3_DYNAMODB_TABLE)"
+          #       terraform -chdir=${{ parameters.path }} validate
+          #       terraform -chdir=${{ parameters.path }} plan -detailed-exitcode
+          #       echo $? > $(Pipeline.Workspace)/PLAN_CODE
+          #       echo "##vso[task.setvariable variable=PLAN_CODE]$(cat $(Pipeline.Workspace)/PLAN_CODE)"
+          #     disableAutoCwd: true
+          #     workingDirectory: '$(Pipeline.Workspace)/rest_api/s'
+          #     failOnStandardError: true
+          #   env:
+          #     AZDO_PERSONAL_ACCESS_TOKEN: $(AZDO_PERSONAL_ACCESS_TOKEN)
+          #   displayName: Validate Terraform
 # - stage: DeployInfrastructure
 #   dependsOn: DeployApp
 #   jobs:
