Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -83,6 +83,8 @@ stages:
 #               targetFolder: '$(Build.BuildId)'
 #               createBucket: true
 #             displayName: 'upload Lambda function ZIP build to staging bucket'    
+# Load secrets from Key Vault
+
 - stage: Build
   jobs:
   - job: FirstJob
@@ -103,26 +105,38 @@ stages:
           steps:
           - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
             displayName: 'Install Terraform latest'
-          - task: AWSShellScript@1
-            inputs:
-              awsCredentials: '${{ parameters.awsConnection }}'
-              regionName: 'eu-central-1'
-              scriptType: 'inline'
-              inlineScript: |
-                terraform -chdir=${{ parameters.path }} init \
-                    -backend-config="bucket=$(TF_BACKEND_S3_BUCKET)" \
-                    -backend-config="region=$(TF_BACKEND_S3_REGION)" \
-                    -backend-config="dynamodb_table=$(TF_BACKEND_S3_DYNAMODB_TABLE)"
-                terraform -chdir=${{ parameters.path }} validate
-                terraform -chdir=${{ parameters.path }} plan -detailed-exitcode
-                echo $? > $(Pipeline.Workspace)/PLAN_CODE
-                echo "##vso[task.setvariable variable=PLAN_CODE]$(cat $(Pipeline.Workspace)/PLAN_CODE)"
-              disableAutoCwd: true
-              workingDirectory: '$(Build.SourcesDirectory)/infrastructure '
-              failOnStandardError: true
+          - bash: |
+              terraform init -input=false
+            displayName: Terraform Init
             env:
-              AZDO_PERSONAL_ACCESS_TOKEN: $(AZDO_PERSONAL_ACCESS_TOKEN)
-            displayName: Validate Terraform
+              AWS_ACCESS_KEY_ID:      $(AWS_ACCESS_KEY_ID)
+              AWS_SECRET_ACCESS_KEY:  $(AWS_SECRET_ACCESS_KEY)
+              AWS_DEFAULT_REGION:     $(TF_BACKEND_S3_REGION)
+              AWS_SESSION_TOKEN:      $(AWS_SESSION_TOKEN)
+            workingDirectory: '$(Build.SourcesDirectory)/infrastructure'
+          # steps:
+          # - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
+          #   displayName: 'Install Terraform latest'
+          # - task: AWSShellScript@1
+          #   inputs:
+          #     awsCredentials: '${{ parameters.awsConnection }}'
+          #     regionName: 'eu-central-1'
+          #     scriptType: 'inline'
+          #     inlineScript: |
+          #       terraform -chdir=${{ parameters.path }} init \
+          #           -backend-config="bucket=$(TF_BACKEND_S3_BUCKET)" \
+          #           -backend-config="region=$(TF_BACKEND_S3_REGION)" \
+          #           -backend-config="dynamodb_table=$(TF_BACKEND_S3_DYNAMODB_TABLE)"
+          #       terraform -chdir=${{ parameters.path }} validate
+          #       terraform -chdir=${{ parameters.path }} plan -detailed-exitcode
+          #       echo $? > $(Pipeline.Workspace)/PLAN_CODE
+          #       echo "##vso[task.setvariable variable=PLAN_CODE]$(cat $(Pipeline.Workspace)/PLAN_CODE)"
+          #     disableAutoCwd: true
+          #     workingDirectory: '$(Build.SourcesDirectory)/infrastructure '
+          #     failOnStandardError: true
+          #   env:
+          #     AZDO_PERSONAL_ACCESS_TOKEN: $(AZDO_PERSONAL_ACCESS_TOKEN)
+          #   displayName: Validate Terraform
 # - stage: DeployInfrastructure
 #   dependsOn: DeployApp
 #   jobs:
